keycloak:
  # 表示是一个public的client
  public-client: true
  # keycloak的地址
  auth-server-url: http://192.168.56.100:8080/auth
  # keycloak中的realm
  realm: realm-test
  resource: spring-keycloak-app
  securityConstraints:
    - authRoles:
        # 以下路径需要user-role角色才能访问
        - test-role
      securityCollections:
        # name可以随便写
        - name: test-role-mappings
          patterns:
            - /articles/*
server:
  port: 8086